apiVersion: v1
kind: Secret
metadata:
  name: members-openshift-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmFwcHMub2NwNC1odWIuZWR3aW4uaG9tZSI6IHsKICAgICAgImF1dGgiOiAiYldWdFltVnljeXR2Y0dWdWMyaHBablE2UVZSVFFqQTBRVE5TV0ZJMVNUUlJObFpET1U1RVVEaEtNVWxNTlRNNU1rSTVWRVl5UWtNeFUxa3pOVk15TjBNd1VFZFVNRFJFUlZGU00xY3lPVlZPV2c9PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson